version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8080"
    volumes:
      - .:/app
    depends_on:
      - mongo
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
